### ISSUE TITLE
Not working on 1.20.1

### ISSUE THREAD

**Issue by aleksandarbst** [camnwalter/ModMenuCommand#1]
Command doesn't seem to work on 1.20.1
Running experimental Distant Horizons instance so that might be the reason, wanted to submit issue in case this is already known.
Fabric API 0.92.0+1.20.1

![image](https://github.com/camnwalter/ModMenuCommand/assets/8200511/92659c0d-9d80-4e40-9cee-474676c5d5ec)

**Comment by camnwalter** [comment]
I'll look into it. Thanks

**Comment by camnwalter** [comment]
Yeah I don't really want to fix that. I'm probably only going to keep it up to date with the latest Minecraft versions with big changes.
